ALTER TABLE "OrganizationMaster"
ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "UserTypeMaster"
ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "UserMaster"
ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "UserAuthProvider"
ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
